# Generated by Django 5.1.5 on 2025-02-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPTV_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='modepass_subscription',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='user_subscription',
            field=models.CharField(default='', max_length=100),
        ),
    ]
