# Generated by Django 5.1.5 on 2025-03-13 02:10

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPTV_api', '0003_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTVChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', imagekit.models.fields.ProcessedImageField(upload_to='logos/')),
            ],
        ),
    ]
