# Generated by Django 5.1.5 on 2025-03-24 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPTV_api', '0006_delete_iptvcompress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceAccess',
        ),
    ]
