# Generated by Django 5.1.5 on 2025-03-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPTV_api', '0008_plan_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
