# Generated by Django 5.1.5 on 2025-03-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPTV_api', '0009_alter_plan_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='slug',
        ),
    ]
