# Generated by Django 5.1.5 on 2025-04-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPTV_api', '0016_plan_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordsDescriptionHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('head_keyword', models.TextField(default='', max_length=500)),
                ('head_description', models.TextField(default='', max_length=500)),
                ('alt_images_base', models.TextField(default='', max_length=200)),
                ('alt_channels', models.TextField(default='', max_length=200)),
                ('alt_series', models.TextField(default='', max_length=200)),
            ],
        ),
    ]
