# Generated by Django 5.1.5 on 2025-03-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_step_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_step_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_step_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_step_4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_step_5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_step_1',
            field=models.ImageField(blank=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_step_2',
            field=models.ImageField(blank=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_step_3',
            field=models.ImageField(blank=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_step_4',
            field=models.ImageField(blank=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_step_5',
            field=models.ImageField(blank=True, upload_to='blog_images/'),
        ),
    ]
