# Generated by Django 5.1.5 on 2025-03-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
